language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.2
  - 2.3
  - ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install:
  - gem update bundler
script: xvfb-run bundle exec rspec
